"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Download, Eye, Code, Share, Check, Star, Calendar, Github, Database } from "lucide-react"
import { AdminDashboard } from "./admin-dashboard"
import { AuthMiddleware } from "./auth-middleware"
import TemplateGenerator from "../app/template/page"

interface PreviewGeneratorProps {
  data: any
  setData: (data: any) => void
}

export function PreviewGenerator({ data, setData }: PreviewGeneratorProps) {
  const [activeTab, setActiveTab] = useState("preview")

  const generateFullTemplate = () => {
    return `// Complete SaaS Template Package
// Generated by PlanCraft

## 📦 Package Contents

### 🔐 Authentication System
- NextAuth.js integration with multiple providers
- User registration and login flows
- Session management and JWT tokens
- Password reset functionality

### 💳 Subscription Management
- Stripe integration for payments
- Subscription lifecycle management
- Plan upgrades and downgrades
- Billing portal and invoices

### 🛡️ Route Protection Middleware
- Protect pages based on authentication status
- Plan-specific access control
- Admin-only routes
- Automatic redirects for unauthorized access

### 📊 Admin Dashboard
- User management interface
- Subscription analytics
- Revenue tracking
- System configuration

### 🗄️ Database Schema
\`\`\`sql
-- Users table
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255),
  role VARCHAR(50) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Subscriptions table
CREATE TABLE subscriptions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  stripe_subscription_id VARCHAR(255),
  plan_name VARCHAR(100),
  status VARCHAR(50),
  current_period_start TIMESTAMP,
  current_period_end TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Credits table (if using credit system)
CREATE TABLE credits (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  credit_type VARCHAR(100),
  amount INTEGER DEFAULT 0,
  expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);
\`\`\`

### 🔧 Environment Variables
\`\`\`env
# Database
DATABASE_URL="postgresql://..."

# NextAuth
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="your-secret-key"

# OAuth Providers
GOOGLE_CLIENT_ID="your-google-client-id"
GOOGLE_CLIENT_SECRET="your-google-client-secret"
GITHUB_CLIENT_ID="your-github-client-id"
GITHUB_CLIENT_SECRET="your-github-client-secret"

# Stripe
STRIPE_PUBLISHABLE_KEY="pk_test_..."
STRIPE_SECRET_KEY="sk_test_..."
STRIPE_WEBHOOK_SECRET="whsec_..."

# Email (Optional)
SMTP_HOST="smtp.gmail.com"
SMTP_PORT="587"
SMTP_USER="your-email@gmail.com"
SMTP_PASS="your-app-password"
\`\`\`

### 🚀 Quick Start
1. Clone the repository
2. Install dependencies: \`npm install\`
3. Set up environment variables
4. Run database migrations: \`npm run db:migrate\`
5. Start development server: \`npm run dev\`

### 📁 Project Structure
\`\`\`
${data.templateConfig?.projectName || "my-saas-app"}/
├── app/
│   ├── (auth)/
│   │   ├── signin/
│   │   ├── signup/
│   │   └── callback/
│   ├── (dashboard)/
│   │   ├── dashboard/
│   │   ├── billing/
│   │   └── settings/
│   ├── admin/
│   │   ├── dashboard/
│   │   ├── users/
│   │   └── subscriptions/
│   ├── api/
│   │   ├── auth/
│   │   ├── webhooks/
│   │   └── subscriptions/
│   └── globals.css
├── components/
│   ├── ui/
│   ├── auth/
│   ├── subscription-plans.tsx
│   ├── admin-dashboard.tsx
│   └── billing-portal.tsx
├── lib/
│   ├── auth.ts
│   ├── db.ts
│   ├── stripe.ts
│   └── utils.ts
├── middleware.ts
├── prisma/
│   ├── schema.prisma
│   └── migrations/
├── .env.example
├── package.json
└── README.md
\`\`\`

### 🎨 Styling
- Tailwind CSS for utility-first styling
- shadcn/ui components for consistent UI
- Dark mode support
- Responsive design

### 🔌 Integrations Included
- Stripe for payments and subscriptions
- NextAuth.js for authentication
- Prisma for database ORM
- React Hook Form for form handling
- Zod for schema validation

### 📧 Email Templates
- Welcome email for new users
- Subscription confirmation
- Payment receipts
- Trial expiration reminders
- Cancellation confirmations

### 🛠️ Development Tools
- TypeScript for type safety
- ESLint and Prettier for code quality
- Husky for git hooks
- Jest for testing
- Storybook for component development

### 📈 Analytics & Monitoring
- Built-in analytics dashboard
- User behavior tracking
- Revenue metrics
- Subscription churn analysis
- Error monitoring setup

This template provides everything you need to launch a production-ready SaaS application with minimal setup required.`
  }

  const colorOptions = [
    {
      name: "Purple",
      value: "purple",
      class: "from-purple-500 to-pink-500",
      bg: "bg-purple-600",
      hover: "hover:bg-purple-700",
    },
    { name: "Blue", value: "blue", class: "from-blue-500 to-cyan-500", bg: "bg-blue-600", hover: "hover:bg-blue-700" },
    {
      name: "Green",
      value: "green",
      class: "from-green-500 to-emerald-500",
      bg: "bg-green-600",
      hover: "hover:bg-green-700",
    },
    {
      name: "Orange",
      value: "orange",
      class: "from-orange-500 to-red-500",
      bg: "bg-orange-600",
      hover: "hover:bg-orange-700",
    },
    {
      name: "Indigo",
      value: "indigo",
      class: "from-indigo-500 to-purple-500",
      bg: "bg-indigo-600",
      hover: "hover:bg-indigo-700",
    },
  ]

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="text-3xl font-bold text-white mb-4">Complete SaaS Solution</h2>
        <p className="text-gray-300 text-lg max-w-2xl mx-auto">
          Preview your subscription plans, admin dashboard, and generate a complete Next.js template
        </p>
      </div>

      {/* Export Actions */}
      <Card className="bg-white/5 border-white/10">
        <CardContent className="p-6">
          <div className="flex flex-wrap gap-4 justify-center">
            <Button className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white">
              <Download className="w-4 h-4 mr-2" />
              Download Complete Template
            </Button>
            <Button variant="outline" className="border-white/20 text-white hover:bg-white/10 bg-transparent">
              <Github className="w-4 h-4 mr-2" />
              Create GitHub Repository
            </Button>
            <Button variant="outline" className="border-white/20 text-white hover:bg-white/10 bg-transparent">
              <Database className="w-4 h-4 mr-2" />
              Deploy with Database
            </Button>
            <Button variant="outline" className="border-white/20 text-white hover:bg-white/10 bg-transparent">
              <Share className="w-4 h-4 mr-2" />
              Share Template
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Preview Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-5 bg-white/10">
          <TabsTrigger value="preview" className="data-[state=active]:bg-white/20 text-white">
            <Eye className="w-4 h-4 mr-2" />
            Plans Preview
          </TabsTrigger>
          <TabsTrigger value="admin" className="data-[state=active]:bg-white/20 text-white">
            Admin Dashboard
          </TabsTrigger>
          <TabsTrigger value="auth" className="data-[state=active]:bg-white/20 text-white">
            Route Protection
          </TabsTrigger>
          <TabsTrigger value="template" className="data-[state=active]:bg-white/20 text-white">
            Template Generator
          </TabsTrigger>
          <TabsTrigger value="code" className="data-[state=active]:bg-white/20 text-white">
            <Code className="w-4 h-4 mr-2" />
            Full Template
          </TabsTrigger>
        </TabsList>

        <TabsContent value="preview" className="mt-6">
          <Card className="bg-white/5 border-white/10">
            <CardHeader>
              <CardTitle className="text-white">Subscription Plans Preview</CardTitle>
              <CardDescription className="text-gray-300">
                See how your subscription plans will look to customers
              </CardDescription>
            </CardHeader>
            <CardContent>
              {/* Plans Preview */}
              {data.plans && data.plans.length > 0 ? (
                <div className="bg-white rounded-lg p-8">
                  <div className="text-center mb-12">
                    <h2 className="text-4xl font-bold text-gray-900 mb-4">Choose Your Plan</h2>
                    <p className="text-xl text-gray-600">Select the perfect plan for your needs</p>
                  </div>

                  <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
                    {data.plans.map((plan: any, index: number) => {
                      const colorOption = colorOptions.find((c) => c.value === plan.color) || colorOptions[0]

                      return (
                        <div
                          key={index}
                          className={`relative bg-white rounded-2xl shadow-xl border-2 transition-transform hover:scale-105 ${
                            plan.highlighted ? "border-purple-500 ring-4 ring-purple-500/20" : "border-gray-200"
                          }`}
                        >
                          {plan.highlighted && (
                            <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
                              <Badge className="bg-gradient-to-r from-purple-500 to-pink-500 text-white px-4 py-1">
                                <Star className="w-3 h-3 mr-1" />
                                Most Popular
                              </Badge>
                            </div>
                          )}

                          <div className="p-8">
                            <h3 className="text-2xl font-bold text-gray-900 mb-2">{plan.name}</h3>
                            <p className="text-gray-600 mb-6">{plan.description}</p>

                            <div className="mb-6">
                              <span className="text-4xl font-bold text-gray-900">${plan.price}</span>
                              <span className="text-gray-600">/{plan.billing}</span>
                            </div>

                            {plan.trialDays > 0 && (
                              <div className="mb-4">
                                <Badge className="bg-green-100 text-green-800">
                                  <Calendar className="w-3 h-3 mr-1" />
                                  {plan.trialDays} day free trial
                                </Badge>
                              </div>
                            )}

                            {plan.setupFee > 0 && (
                              <div className="mb-4">
                                <span className="text-sm text-gray-600">Setup fee: ${plan.setupFee}</span>
                              </div>
                            )}

                            <ul className="space-y-3 mb-8">
                              {(plan.features || []).map((feature: any, featureIndex: number) => (
                                <li key={featureIndex} className="flex items-center">
                                  {feature.included ? (
                                    <Check className="w-5 h-5 text-green-500 mr-3" />
                                  ) : (
                                    <div className="w-5 h-5 mr-3 flex items-center justify-center">
                                      <div className="w-3 h-3 bg-gray-300 rounded-full" />
                                    </div>
                                  )}
                                  <span
                                    className={`${feature.included ? "text-gray-700" : "text-gray-400 line-through"}`}
                                  >
                                    {feature.text}
                                  </span>
                                </li>
                              ))}
                            </ul>

                            <button
                              className={`w-full py-3 px-6 rounded-lg font-semibold transition-colors ${
                                plan.highlighted
                                  ? `bg-gradient-to-r ${colorOption.class} text-white hover:opacity-90`
                                  : "bg-gray-100 text-gray-900 hover:bg-gray-200"
                              }`}
                            >
                              {plan.buttonText || "Get Started"}
                            </button>
                          </div>
                        </div>
                      )
                    })}
                  </div>

                  {/* Credit System Preview */}
                  {data.creditSystem?.enabled && data.creditSystem.packages?.length > 0 && (
                    <div className="mt-16 pt-16 border-t border-gray-200">
                      <div className="text-center mb-12">
                        <h2 className="text-4xl font-bold text-gray-900 mb-4">Credit Packages</h2>
                        <p className="text-xl text-gray-600">Purchase credits for flexible usage</p>
                      </div>

                      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-4xl mx-auto">
                        {data.creditSystem.packages.map((pkg: any, index: number) => (
                          <div
                            key={index}
                            className={`bg-white rounded-xl shadow-lg border-2 p-6 ${
                              pkg.popular ? "border-purple-500 ring-2 ring-purple-500/20" : "border-gray-200"
                            }`}
                          >
                            {pkg.popular && (
                              <Badge className="bg-gradient-to-r from-purple-500 to-pink-500 text-white mb-4">
                                Popular
                              </Badge>
                            )}
                            <h3 className="text-xl font-bold text-gray-900 mb-2">{pkg.name}</h3>
                            <div className="text-3xl font-bold text-gray-900 mb-2">
                              {(pkg.credits + pkg.bonus).toLocaleString()} Credits
                            </div>
                            <div className="text-2xl text-purple-600 font-semibold mb-4">${pkg.price}</div>
                            {pkg.bonus > 0 && (
                              <Badge variant="secondary" className="bg-green-100 text-green-800 mb-4">
                                +{pkg.bonus} Bonus Credits
                              </Badge>
                            )}
                            <div className="text-sm text-gray-600 mb-4">Valid for {pkg.validityDays} days</div>
                            <button className="w-full bg-gradient-to-r from-purple-500 to-pink-500 text-white py-2 px-4 rounded-lg font-semibold hover:opacity-90 transition-opacity">
                              Purchase Credits
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="text-center py-12">
                  <div className="w-16 h-16 bg-gray-200 rounded-full flex items-center justify-center mx-auto mb-4">
                    <Eye className="w-8 h-8 text-gray-400" />
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-2">No Plans to Preview</h3>
                  <p className="text-gray-400">Go back and create some plans to see the preview</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="admin" className="mt-6">
          <AdminDashboard />
        </TabsContent>

        <TabsContent value="auth" className="mt-6">
          <AuthMiddleware data={data} setData={setData} />
        </TabsContent>

        <TabsContent value="template" className="mt-6">
          <TemplateGenerator data={data} setData={setData} />
        </TabsContent>

        <TabsContent value="code" className="mt-6">
          <Card className="bg-white/5 border-white/10">
            <CardHeader>
              <CardTitle className="text-white">Complete SaaS Template</CardTitle>
              <CardDescription className="text-gray-300">
                Full documentation and setup guide for your generated template
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="relative">
                <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto text-sm max-h-96">
                  <code>{generateFullTemplate()}</code>
                </pre>
                <Button
                  size="sm"
                  className="absolute top-2 right-2 bg-white/10 hover:bg-white/20 text-white"
                  onClick={() => navigator.clipboard.writeText(generateFullTemplate())}
                >
                  Copy Template
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
